#!/bin/bash

DNS_IP=172.17.42.1
DNS_FALLBACK_IP=8.8.8.8
DNS_PORT=53
DOMAIN="crook.io"
ENVIRONMENT="dev"
PUPPET_MASTER_HOSTNAME=puppetmaster1.puppet_master.$ENVIRONMENT.$DOMAIN
PUPPET_MASTER_PORT=8140

pushd .

echo "Creating puppet agent docker image..."
cd /vagrant/docker/puppet_agent
docker build -t 'puppet_agent' .

echo "Creating puppet master docker image..."
cd /vagrant/docker/puppet_master
docker build -t 'puppet_master' .

popd

docker pull crosbymichael/skydns

docker run -d -p $DNS_IP:$DNS_PORT:$DNS_PORT/udp \
 --name skydns crosbymichael/skydns \
 -nameserver $DNS_FALLBACK_IP:$DNS_PORT \
 -domain $DOMAIN

docker pull crosbymichael/skydock

docker run -d -v /var/run/docker.sock:/docker.sock \
 --name skydock \
 -link skydns:skydns crosbymichael/skydock \
 -ttl 30 -environment $ENVIRONMENT \
 -s /docker.sock -domain $DOMAIN

docker run -t -h $PUPPET_MASTER_HOSTNAME \
 --name puppetmaster1 \
 --dns $DNS_IP \
 -p $PUPPET_MASTER_PORT:$PUPPET_MASTER_PORT \
 -i -d puppet_master /usr/bin/puppet master \
 --mkusers --autosign true --no-daemonize --verbose --debug

for h in api1 db1; do
 host="$h.puppet_agent.$ENVIRONMENT.$DOMAIN"
 echo "Starting container for $host"
 docker run -t -h $host --dns $DNS_IP --name $h -i -d puppet_agent /usr/bin/puppet agent --certname $h --server $PUPPET_MASTER_HOSTNAME --no-daemonize --verbose --debug
done
